cloud:
  aws:
    region:
      static: region
    stack:
      auto: false
    credentials:
      access-key: key
      secret-key: secret
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
